services:
  - type: web
    name: flashcardapp
    env: python
    buildCommand: ""
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
    disk:
      name: flashcard-storage
      mountPath: /var/data
      sizeGB: 1
